### ISSUE TITLE
Potential error when running multiple jobs simultaneously

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/microservice#25]
Getting a `"sh: cd: line 1: can't cd to /opt/app/project/node_modules: No such file or directory"` when attempting to run a project that triggers 3 jobs simultaneously from an inbound message:
 
```sh
web_1  | [info] POST /inbox
web_1  | [debug] Processing with MicroserviceWeb.Receiver.receive/2
web_1  |   Parameters: %{"__query_params" => %{}, "a" => 1, "baz" => "qux", "foo" => "other thing", "form" => "COVID_case_registration", "formId" => "Tier_2_Needs_Assessment_v4", "from" => "OpenFn", "ju_ju" => "bean", "nüumber" => 2, "surveyId" => 37479}
web_1  |   Pipelines: [:api]
web_1  | [debug] Receiver.receive/2 called
web_1  | [debug] env: NODE_PATH=/opt/app/project/node_modules
web_1  | cmd:   (cd $NODE_PATH && ./.bin/core execute   -e /opt/app/tmp/expression-1619185429-1-cz7ixx.js   -l @openfn/language-dhis2@v2.0.4   -s /opt/app/tmp/state-1619185429-1-1kp57ip.json   -o /opt/app/tmp/final_state-1619185429-1-ezb5td.json 
web_1  |   
web_1  |   
web_1  |   )
web_1  | 
web_1  | 
web_1  | [debug] env: NODE_PATH=/opt/app/project/node_modules
web_1  | cmd:   (cd $NODE_PATH && ./.bin/core execute   -e /opt/app/tmp/expression-1619185429-1-13qlsku.js   -l @openfn/language-googlesheets@v1.0.2   -s /opt/app/tmp/state-1619185429-1-1igdd2z.json   -o /opt/app/tmp/final_state-1619185429-1-nnmxoe.json 
web_1  |   
web_1  |   
web_1  |   )
web_1  | 
web_1  | 
web_1  | [debug] env: NODE_PATH=/opt/app/project/node_modules
web_1  | cmd:   (cd $NODE_PATH && ./.bin/core execute   -e /opt/app/tmp/expression-1619185429-1-1tww7ug.js   -l @openfn/language-salesforce@v1.3.2   -s /opt/app/tmp/state-1619185429-1-14cmllp.json   -o /opt/app/tmp/final_state-1619185429-1-1kzuq7v.json 
web_1  |   
web_1  |   
web_1  |   )
web_1  | 
web_1  | 
web_1  | [info] Sent 202 in 4ms
web_1  | [debug] "sh: cd: line 1: can't cd to /opt/app/project/node_modules: No such file or directory"
web_1  | [debug] "sh: cd: line 1: can't cd to /opt/app/project/node_modules: No such file or directory"
web_1  | [debug] "sh: cd: line 1: can't cd to /opt/app/project/node_modules: No such file or directory"
```

Using the following `project.yaml`:
```yml
credentials:
  dhis2-play-covid-action:
    hostUrl: '******'
    password: '******'
    username: '******'
  google:
    accessToken: '******'
    expiresIn: '******'
    familyName: '******'
    givenName: '******'
    id: '******'
    idToken: '******'
    locale: '******'
    name: '******'
    picture: '******'
    refreshToken: '******'
    scope: '******'
    tokenType: '******'
  salesforce:
    loginUrl: '******'
    password: '******'
    securityToken: '******'
    username: '******'
jobs:
  covid-19-tei-(dhis2):
    adaptor: '@openfn/language-dhis2@v2.0.4'
    credential: 'dhis2-play-covid-action'
    expression: >
      // See list of cases here: https://covid19.dhis2.org/demo/dhis-web-tracker-capture/index.html#/?program=DM9n1bUw8W8
      createTEI({
        orgUnit: 'GD7TowwI46c',
        trackedEntityType: 'MCPQUTHX1Ze',
        attributes: [
          {
            attribute: 'he05i8FUwu3', // case id
            value: dataValue('body._id'),
          },
          {
            attribute: 'sB1IHYu2xQT', // first name
            value: dataValue('body.Patient_name'),
          },
          {
            attribute: 'ENRjVGxVL6l', // last name
            value: dataValue('body.Last_Name_of_Patient'),
          },
          {
            attribute: 'Rv8WM2mTuS5', // age
            value: dataValue('body.Age'),
          },
        ],
        enrollments: [
          {
            orgUnit: 'GD7TowwI46c',
            program: 'DM9n1bUw8W8',
            programState: 'sAV9jAajr8x',
            enrollmentDate: dataValue('body.Date'),
            incidentDate: dataValue('body.Covid_19_suspected_criteria/Speciman_Collection_date')
          },
        ],
      });
    trigger: 'covid-case-submitted'
  covid-case-registration-(gs):
    adaptor: '@openfn/language-googlesheets@v1.0.2'
    credential: 'google'
    expression: >
      appendValues({
        spreadsheetId: '1EFkY4zD4qqxnJdH-QaeasKd1zXC-1sNKpEg08W-3sT0',
        range: 'COVID-19 Cases!A2',
        values: state => {
          const kobo = state.data.body;
          
          console.log('Submission data: ' + JSON.stringify(kobo, null, 2));
          
          return [
            [
              kobo['National_ID'],
              kobo['Patient_name'],
              kobo['Last_Name_of_Patient'],
              kobo['Sex'],
              kobo['Age'],
              kobo['Comments'],
              kobo['Date']
            ],
          ];
        },
      });
    trigger: 'covid-case-submitted'
  create-sf-contact:
    adaptor: '@openfn/language-salesforce@v1.3.2'
    credential: 'salesforce'
    expression: >
      create('Contact', {
        FirstName: dataValue("body.Patient_name"),
        LastName: dataValue('body.Last_Name_of_Patient'),
        Age__c: dataValue("body.Age"),
        Sex__c: dataValue("body.Sex"),	
        Case_ID__c: dataValue("body.National_ID"),	
        Comments__c: dataValue("body.Comments")
      });
    trigger: 'covid-case-submitted'
triggers:
  covid-case-submitted:
    criteria: '{"form":"COVID_case_registration"}'
```
